//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elearn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class exame
    {
        public int id { get; set; }
        public string photo { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public Nullable<int> id_emp { get; set; }
        public Nullable<int> id_teacher { get; set; }
        public Nullable<int> idgroup { get; set; }
    }
}
