//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elearn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ueaser
    {
        public int id { get; set; }
        public string Fname { get; set; }
        public string Lname { get; set; }
        public string phone { get; set; }
        public Nullable<int> role { get; set; }
        public string UserName { get; set; }
        public string Pass { get; set; }
        public Nullable<int> actv { get; set; }
        public string sex { get; set; }
    }
}
